import{S as q,i as a,a as E}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const O=document.querySelector(".form"),l=document.querySelector(".gallery-grid"),g=document.querySelector(".loader"),f=document.querySelector(".js-target");let M=new q(".gallery-grid a",{captionsData:"alt"}),c=1,u,p=0;O.addEventListener("submit",$);const P=(s,e)=>{s.forEach(r=>{r.isIntersecting&&H()})},m=new IntersectionObserver(P);async function $(s){var e;if(s.preventDefault(),d(),l.innerHTML="",u=s.target.elements.query.value.trim(),!u){l.innerHTML="",a.error({message:"Search field is empty",position:"topRight"});return}h();try{c=1;const r=await S();if((e=r==null?void 0:r.hits)!=null&&e.length){b(),p=Math.ceil(r.totalHits/15),y(),w(r.hits);return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(r){a.info({message:typeof r=="string"?r:"Something went wrong, sorry!",position:"topRight"})}s.target.reset()}async function H(){var s;h(),d();try{c+=1;const e=await S();if((s=e==null?void 0:e.hits)!=null&&s.length){b(),y(),w(e.hits);const r=document.querySelector(".gallery-card").getBoundingClientRect().height;scrollBy({top:r*2,behavior:"smooth"});return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){a.info({message:typeof e=="string"?e:"Something went wrong, sorry!",position:"topRight"})}}function y(){p!==c?I():(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function h(){g.style.display="inline-block"}function b(){g.style.display="none"}function I(){m.observe(f)}function d(){m.unobserve(f)}async function S(){return(await E.get("https://pixabay.com/api/",{params:{key:"42157668-d969611c6fdd34526589fe987",q:u,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:c,per_page:15}})).data}function w(s){const e=s.map(({webformatURL:r,largeImageURL:n,tags:t,likes:o,views:i,comments:v,downloads:L})=>`<a href="${n}" class="gallery-card">
      <img src="${r}" alt="${t}" >
      <div class="img-details-box">
      <p class="detail-item"><b>Likes:</b> ${o}</p>
      <p class="detail-item"><b>Views:</b> ${i}</p>
      <p class="detail-item"><b>Comments:</b> ${v}</p>
      <p class="detail-item"><b>Downloads:</b> ${L}</p></div>
      </a>`).join("");l.insertAdjacentHTML("beforeend",e),M.refresh()}
//# sourceMappingURL=commonHelpers.js.map
